# Mi primera sentencia en Python
print("Hola Mundo")
print(3+3)
print(3*3)
print("Hola, soy un \"mensaje\" con comillas")
print("Hola, soy un 'mensaje' con comillas")
print("Mi nombre es: \n\tJuan")
print("Tu nombre es " + input("¿Cómo te llamas? "))
numero1 = input("Dame un número: ")
print("El número que me diste es: " + numero1)